config/routes.rb
Rails.application.routes.draw do
  root 'inventory#all_products'
  get 'one_product' => 'inventory#one_product'
  get 'by_category' => 'inventory#by_category'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/inventory_controller.rb
class InventoryController < ApplicationController
  def all_products
  	@products = Product.all
  end

  def one_product
  	@product = Product.find(params[:id])
  end

  def by_category
  	@products = Product.where(category: params[:category])

  	@category = params[:category]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inventory_helper.rb
module InventoryHelper
end

app/views/inventory/all_products.html.erb
<h1>Welcome to the Furniture Store!</h1>
<p>See all of your products below:</p>
<table>
	<tr>
		<th>Name</th>
		<th>Price</th>
		<th>Category</th>
	</tr>
	<% @products.each do |product| %>
	<tr>
		<td><%= link_to product.name, one_product_path(id: product.id) %></td>
		<td><%= number_to_currency product.price %></td>
		<td><%= link_to product.category, by_category_path(category: product.category) %></td>
	</tr>
	<% end %>
</table>

app/views/inventory/by_category.html.erb
<h1>Welcome to the Furniture Store!</h1>
<p>See all of our products in our <%= @category %> Category:</p>
<table>
	<tr>
		<th>Name</th>
		<th>Price</th>
		<th>Category</th>
	</tr>
	<% @products.each do |product| %>
	<tr>
		<td><%= link_to product.name, one_product_path(id: product.id) %></td>
		<td><%= number_to_currency product.price %></td>
	</tr>
	<% end %>
</table>
<br>
<%= link_to "Back to All Products", root_path %>

app/views/inventory/one_product.html.erb
<h1>Here is info about this product:</h1>
<p>Product name: <%= @product.name %></p>
<p>Product Price: <%= number_to_currency @product.price %></p>
<p>Product Category: <%= link_to @product.category, by_category_path(category: @product.category) %></p>
<br>
<%= link_to "Back to All Products", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FurnitureStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>